name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} жестко накомитил:
            ${{ github.event.commits[0].message }}

            Куда?: ${{ github.repository }}

            Коммит: https://github.com/${{ github.repository }}/commit/${{github.sha}}

  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: build
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2

  third-job:
    runs-on: ubuntu-latest
    name: slave
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            numpy
            matplotlib
            sklearn
            scikit-image
            torch
      - run: python main.py

      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: results.txt
          message: |
            пришли анализы
